jobs:
  porter-deploy:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: vars
        name: Set Github tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - env:
          DOCKER_BUILDKIT: "1"
          PORTER_APP_NAME: pretty-simple-app
          PORTER_BUILDKIT_ARGS: --platform linux/arm64
          PORTER_BUILDKIT_PUSH_ARGS: --platform linux/arm64
          PORTER_CLUSTER: "5365"
          PORTER_DEPLOYMENT_TARGET_ID: 8345dd30-482a-4891-abbf-6a578f17265d
          PORTER_HOST: https://dashboard.porter.run
          PORTER_PROJECT: "13871"
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_13871_869691824 }}
        name: Deploy stack
        run: porter apply -f porter.yaml --exact
        timeout-minutes: 30

name: Deploy to pretty-simple-app

"on":
  push:
    branches:
      - master
  workflow_dispatch: {}
